lottery_ticket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("number_generator.urls"))
]

number_generator/urls.py
from django.urls import path, register_converter
from . import views, converters

register_converter(converters.SixDigitConverter, "dddddd")

app_name = "number_generator"

urlpatterns = [
    path("", views.RedirectToHomeView.as_view(), name="root_page"),
    path("home/", views.homeView, name="home_page"),
    path("generation/<dddddd:pk>/", views.GenerationDetailView.as_view(), name="generation_detail_page"),
    path("generation/", views.GenerationListView.as_view(), name="generation_listing_page"),
    path("about/", views.AboutView.as_view(), name="about_page"),
]

number_generator/models.py
from django.db import models
from uuid import uuid4
from random import seed, randint, choice

class Generation(models.Model):
    guid = models.UUIDField(unique=True, default=uuid4)
    public_unique_identifier = models.BigAutoField(primary_key=True)
    range_from = models.PositiveSmallIntegerField()
    range_to = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def get_formatted_puid(self):
        return "#" + "%06d" % self.public_unique_identifier

    def generateRandomNumbers(
        self,
        quantity: int,
        rand_seed = None,
    ):
        seed(rand_seed)

        generatedNumbers = list()
        availableNumbers = [ x for x in range(self.range_from, self.range_to + 1) ]
        for _ in range(quantity):
            randomIndex = randint(0, len(availableNumbers) - 1)
            drawnNumber = availableNumbers.pop(randomIndex)
            generatedNumbers.append(drawnNumber)

        numbers = list()
        for generatedNumber in generatedNumbers:
            number = Number()
            number.generation = self
            number.number = generatedNumber
            number.color = Number.randomColorEnum()
            numbers.append(number)
        
        return numbers

    def get_numbers(self):
        return Number.objects.all().filter(generation=self.guid)
    
    def get_numbers_sorted(self, max_quantity = None):
        queryset = self.get_numbers().order_by("number")
        if max_quantity:
            return queryset[:max_quantity]
        return queryset
    
    def get_ten_numbers_sorted(self):
        return self.get_numbers_sorted(10)

class Number(models.Model):
    COLOR_ENUM = {
        "RED": "Red",
        "BLUE": "Blue",
        "GREEN": "Green",
        "PURPLE": "Purple",
    }

    guid = models.UUIDField(primary_key=True, default=uuid4)
    generation = models.ForeignKey(
        Generation,
        on_delete=models.CASCADE,
        to_field="guid"
    )
    color = models.CharField(max_length=6, choices=COLOR_ENUM)
    number = models.PositiveSmallIntegerField()

    @staticmethod
    def randomColorEnum():
        return choice(list(Number.COLOR_ENUM.keys()))

number_generator/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.views.generic import DetailView, FormView, ListView, RedirectView, TemplateView
from django.db import IntegrityError, transaction
from django.http import HttpResponseNotFound

from .models import Generation

APP_NAME = "number_generator"

class RedirectToHomeView(RedirectView):
    pattern_name = f"{APP_NAME}:home_page"
    permanent = True

class HomeView(TemplateView):
    template_name = f"{APP_NAME}/home.html"

def homeViewPOST(request):
    TEMPLATE_NAME = f"{APP_NAME}/home.html"
    error_list = list()

    quantity = request.POST["quantity"]
    range_from = request.POST["range_from"]
    range_to = request.POST["range_to"]

    isQuantityInteger = quantity.isdecimal() or quantity[1:].isdecimal()
    isRangeFromInteger = range_from.isdecimal() or range_from[1:].isdecimal()
    isRangeToInteger = range_to.isdecimal() or range_to[1:].isdecimal()
    isInputInteger = isQuantityInteger and isRangeFromInteger and isRangeToInteger
    if not isInputInteger:
        error_list.append("Fields must be integer numbers.")
        return render(request, TEMPLATE_NAME, { "error_list": error_list })

    quantity = int(request.POST["quantity"])
    range_from = int(request.POST["range_from"])
    range_to = int(request.POST["range_to"])

    range_min = min(range_from, range_to)
    range_max = max(range_from, range_to)

    # checks for quantity erros
    isQuantityBelowOne = quantity < 1
    if isQuantityBelowOne:
        error_list.append("Quantity must be a positive integer above zero.")

    isQuantityGreaterThanOneHundred = quantity > 100
    if isQuantityGreaterThanOneHundred:
        error_list.append("Quantity must be equal or below 100.")

    # checks for ranges errors
    isStartingRangeBelowZero = range_min < 0
    if isStartingRangeBelowZero:
        error_list.append("The starting range must be a positive integer.")
    
    isEndingRangeAboveNinetyNine = range_max > 99
    if isEndingRangeAboveNinetyNine:
        error_list.append("The ending range must be equal or lower than 99.")

    range_size = range_max - range_min + 1
    isQuantityGreaterThanRangeSize = quantity > range_size
    if isQuantityGreaterThanRangeSize:
        error_list.append("Can not generate more numbers than exists within the specified range.")
    
    # return the feedback to user if there is any error
    hasErrorMessages = len(error_list) > 0
    if hasErrorMessages:
        return render(request, TEMPLATE_NAME, { "error_list": error_list })

    try:
        with transaction.atomic():
            generation = Generation()
            generation.range_from = range_min
            generation.range_to = range_max
            generation.save()

            randomNumbers = generation.generateRandomNumbers(quantity)
            for number in randomNumbers:
                number.save()
    except IntegrityError:
        error_list.append("Something went wrong :(. Contact an administrator and trying again later.")
        return render(request, TEMPLATE_NAME, { "error_list": error_list }, status=500)
    return redirect(
        "number_generator:generation_detail_page",
        pk=(generation.public_unique_identifier),
    )

def homeViewALL(request):
    TEMPLATE_NAME = f"{APP_NAME}/home.html"
    return render(request, TEMPLATE_NAME)

def homeView(request):
    if request.method == "POST":
        return homeViewPOST(request)
    return homeViewALL(request)

class GenerationDetailView(DetailView):
    template_name = f"{APP_NAME}/generation_detail.html"
    model = Generation

class GenerationListView(ListView):
    model = Generation
    template_name = f"{APP_NAME}/generation_list.html"
    paginate_by = 10

    def get_queryset(self):
        return super().get_queryset().order_by("-created_at")

class AboutView(TemplateView):
    template_name = f"{APP_NAME}/about.html"

number_generator/templates/number_generator/about.html
{% extends "number_generator/base.html" %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "number_generator/style_about.css" %}" />
{% endblock %}
{% block title %}About{% endblock %}
{% block about_selected%}selected{% endblock %}

{% block content %}
<div id="content">
    <h1>About</h1>
    <div id="logo_about"><img src="{% static "number_generator/logo.png" %}" /></div>

    <p>
        Lottery Ticketz is a fictional trademark created for this web application project, it is part of the
        portfolio of Lucas Gonçalves Cordeiro, a Software Engineer with focus on backend development.
        You can find more about the developer on <a href="https://github.com/LucasKodex" target="_blank">GitHub</a>
        and on <a href="https://www.linkedin.com/in/lucas-gon%C3%A7alves-cordeiro/" target="_blank">LinkedIn</a>.
        This web application is a simple number generator that was made thinking in lottery draws, developed
        with Python using Django framework.
    </p>

    <div id="buttons">
        <a href="https://github.com/LucasKodex" target="_blank"><button id="btn_github" class="btn btn_main"><img class="img_icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" />GITHUB</button></a>
        <a href="https://www.linkedin.com/in/lucas-gon%C3%A7alves-cordeiro/" target="_blank"><button id="btn_linkedin" class="btn btn_main"><img class="img_icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-plain.svg" />LINKEDIN</button></a>
    </div>
</div>
{% endblock %}

number_generator/templates/number_generator/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        {% block head %}{% endblock %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Page{% endblock %} - Lottery Numberz</title>
        <link rel="icon" type="image/x-icon" href="{% static "number_generator/favicon.png" %}" />
        <link rel="stylesheet" href="{% static "number_generator/style_base.css" %}" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;700&display=swap" />
    </head>
    <body>
        <header>
            <div id="logo">
                <a href="{% url "number_generator:home_page" %}" ><img src="{% static "number_generator/logo.png" %}" id="logo-img" /></a>
            </div>
                
            <div id="links">
                <a href="{% url "number_generator:home_page" %}"><div class="{% block home_selected %}{% endblock %} nav_btn" >Home</div></a>
                <a href="{% url "number_generator:about_page" %}"><div class="{% block about_selected %}{% endblock %} nav_btn" >About</div></a>
                <a href="{% url "number_generator:generation_listing_page" %}"><div class="{% block generations_selected %}{% endblock %} nav_btn" >Other Generations</div></a>
            </div>
        </header>
        
        <main>
            {% block content %}{% endblock %}
        </main>
        
        <footer>
            <div>Author &commat; <a href="https://github.com/LucasKodex" target="_blank">Lucas Gonçalves Cordeiro</a> - 2024</div>
        </footer>
    </body>
</html>

number_generator/templates/number_generator/generation_detail.html
{% extends "number_generator/base.html" %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "number_generator/style_generation_detail.css" %}" />
{% endblock %}
{% block title %}Generation Details{% endblock %}

{% block content %}
<div id="generation_detail">
    <div id="lucky_title">
        <h1>YOUR LUCKY NUMBERS</h1>
        <p>{{ generation.get_formatted_puid }}</p>
    </div>

    <ul>
        {% for number in generation.get_numbers_sorted %}
        <li class="color_{{ number.color | lower }}">{{ number.number }}</li>
        {% endfor %}
    </ul>
    
    <div id="buttons">
        <div>
            <button id="share" type="button" class="btn btn_main" onclick="shareButton()">
                {{ "Share" | upper }}
            </button>
        </div>
        <div>
            <button type="button" class="btn btn_back" onclick="history.back()">
                {{ "Back" | upper }}
            </button>
        </div>
    </div>
</div>
<script>
    let originalShareButtonContent = (() => {
        const button = window.document.querySelector("button#share");
        const buttonContent = button.innerHTML;
        return buttonContent;
    })();

    async function shareButton() {
        const location = window.location.href;
        await navigator.clipboard.writeText(location);

        const button = window.document.querySelector("button#share");
        const TWO_SECONDS = 2000;
        const timeout = TWO_SECONDS;
        button.innerHTML = "Copied!"
        setTimeout(() => {
            button.innerHTML = originalShareButtonContent;
        },
        timeout);
    }
</script>

{% endblock %}

number_generator/templates/number_generator/generation_list.html
{% extends "number_generator/base.html" %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "number_generator/style_generation_list.css" %}" />
{% endblock %}
{% block title %}Generation List{% endblock %}
{% block generations_selected%}selected{% endblock %}

{% block content %}
<div id="content">
    {% if generation_list %}
    <h1>Other generated numbers</h1>
    <ul id="generation_list">
        {% for generation in page_obj %}
        <li>
            <p class="puid">{{ generation.get_formatted_puid }}</p>
            <div class="generation_numbers">
                <ul class="number_list">
                    {% for number in generation.get_ten_numbers_sorted %}
                    <li class="color_{{ number.color | lower }}">
                        {{ number.number }}
                    </li>
                    {% endfor %}
                </ul>
                <div>
                    Count: {{ generation.get_numbers | length }}
                </div>
                <a href="{% url "number_generator:generation_detail_page" generation.public_unique_identifier %}">
                    <button class="btn btn_main">
                        {{ "View" | upper }}
                    </button>
                </a>
            </div>
        </li>
        {% endfor %}
    </ul>

    <div id="paging">
        {% if page_obj.has_previous %}
        <a id="btn_prev" href="?page={{ page_obj.previous_page_number }}">
            <button class="btn btn_back">
                Previous
            </button>
        </a>
        {% endif %}
        <div id="page_number">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </div>
        {% if page_obj.has_next %}
        <a id="btn_next" href="?page={{ page_obj.next_page_number }}">
            <button class="btn btn_main">
                Next
            </button>
        </a>
        {% endif %}
    </div>
    {% else %}
    <h1>There's no generations yet</h1>
    {% endif %}
</div>
{% endblock %}

number_generator/templates/number_generator/home.html
{% extends "number_generator/base.html" %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static "number_generator/style_home.css" %}" />
{% endblock %}
{% block title %}Home{% endblock %}
{% block home_selected%}selected{% endblock %}

{% block content %}
<div id="generation_form">
    <form action="{% url "number_generator:home_page" %}" method="post">
        {% csrf_token %}
        <label for="number_quantity">How many numbers do you want to generate?</label>
        <input type="number" min="1" max="1002" placeholder="6" id="number_quantity" name="quantity" class="number quantity" />
        <fieldset>
            <legend>Which is the range of numbers?</legend>
            <input type="number" min="0" max="99" placeholder="0" id="range_from" name="range_from" class="number range" />
            <label>to</label>
            <input type="number" min="0" max="99" placeholder="99" id="range_to" name="range_to" class="number range" />
        </fieldset>

        {% if error_list %}
        <div id="errors">
            <ul>
                {% for error in error_list %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        
        <input type="submit" value="{{ "Generate" | upper }}" class="btn btn_main" />
    </form>
</div>
{% endblock %}